### ISSUE TITLE
`check_resources` update for wpia cluster?

### ISSUE THREAD

**Issue by OJWatson** [mrc-ide/didehpc#117]
This may be expected behaviour, but if you ask for a default config on the new `wpia` clusters, `check_resources` will return `type = Nodes`. 

```
didehpc::didehpc_config(use_workers = TRUE, cluster = "wpia-hn")
<didehpc_config>
- cluster: wpia-hn
- credentials:
    - username: ow813
    - password: *******************
- username: ow813
- resource:
    - template: AllNodes
    - parallel: TRUE
    - count: 1
    - type: Nodes
- shares:
    - home: (local) L: => \\fi--didenas5.dide.ic.ac.uk\malaria => L: (remote)
    - temp: (local) T: => \\fi--didef3.dide.ic.ac.uk\tmp => T: (remote)
- use_workers: TRUE
- use_rrq: FALSE
- worker_timeout: 600
- conan_bootstrap: TRUE
- r_version: 4.2.3
- use_java: FALSE
- redis_host: wpia-hn.hpc.dide.ic.ac.uk
```

In `didehpc:::check_resources()` the if statements check whether you have explicitly asked for cores, but if you specify nothing for cores or template, then it will return `type = Nodes` when on `wpia` cluster. However, on the non-wpia clusters, it would return `type = Cores` by default because the default `template` would be one of `c("GeneralNodes", "Training")`. 

I am not sure if this is expected behaviour, or whether `AllNodes` (the default template for `wpia` clusters) needs to be included in the following line. This would then force users who want to request Nodes as the resource to have to specify `wholenode = TRUE`. 

https://github.com/mrc-ide/didehpc/blob/7559c247936c9c2b6db2330fae8269dc552bf2ad/R/config.R#L434

Have been chatting to @weshinsley about this today, as I was accidentally sending off jobs that were requesting a full node, but only using a single core. Whereas with the same code targetted at the old cluster, I would be correctly taking up just one core. 

Not sure what the correct fix/logic should be but thought i'd mention it :)
